sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '14'
script:
  - npm run lint
  - npm run build
after_success:
  # Deploy code coverage report to codecov.io
  - npm run test:coverage:deploy
